title: Sonia's Lovelace
views:
  - path: default_view
    title: Home
    icon: 'mdi:home-assistant'
    panel: false
    badges: []
    cards:
      - type: entities
        entities:
          - type: 'custom:slider-entity-row'
            entity: light.parlor_shelve_light
            toggle: true
            hide_when_off: true
          - type: 'custom:slider-entity-row'
            entity: light.stairs_led
            toggle: true
            hide_when_off: true
          - type: 'custom:slider-entity-row'
            entity: light.bathroom
            toggle: true
            hide_when_off: true
          - entity: switch.tv
            tab_action:
              action: toggle
          - entity: switch.printer
            tab_action:
              action: call-service
              service: switch.toggle
              service_data:
                entity: switch.printer
          - entity: input_boolean.presence
        show_header_toggle: false
        state_color: true
      - type: horizontal-stack
        cards:
          - type: button
            entity: script.lights_off
            tap_action:
              action: call-service
              service: script.lights_off
              confirmation:
                text: Are you sure you want to turn off all lights?
            name: Lights Off
            icon_height: 50px
          - type: button
            entity: script.set_daytime_to_night
            tap_action:
              action: call-service
              service: script.set_daytime_to_night
              confirmation:
                text: |
                  Do you really want to set the day state to night?

                  This turns lights and switches off!
            name: State Night
            icon_height: 50px
          - type: button
            entity: script.bathroom_demo
            tap_action:
              action: call-service
              service: script.bathroom_demo
              confirmation:
                text: Are you sure you want to run the bathroom demo?
            name: Bathroom Demo
            icon_height: 50px
  - icon: 'mdi:blinds'
    title: Blinds
    path: blinds
    panel: true
    badges: []
    cards: []
  - title: Status
    path: status
    icon: 'mdi:information'
    panel: true
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: glance
                entities:
                  - entity: person.christian_schwarzgruber
                state_color: true
                columns: 1
              - type: button
                entity: input_boolean.presence
                name: Presence
                show_state: true
                icon_height: 50px
                tap_action:
                  action: call-service
                  service: input_boolean.toggle
                  confirmation:
                    text: Toggle presence?
              - type: glance
                entities:
                  - entity: person.sonia_avramidis
                state_color: true
                columns: 1
          - type: glance
            entities:
              - entity: input_boolean.presence
              - entity: input_select.daytime
              - entity: sensor.daylight
              - entity: binary_sensor.workday_sensor
              - entity: sun.sun
              - entity: binary_sensor.bedroom_motion
            state_color: true
            columns: 3
          - type: 'custom:battery-state-card'
            entities:
              - entity: sensor.tablet_battery_level
                name: Tablet Battery
              - entity: sensor.bedroom_motion_battery_level
                name: Bedroom Motion Battery
              - entity: sensor.bath_switch_battery_level
                name: Bath Switch Battery
