title: Sonia's Lovelace
views:
  - path: default_view
    title: Home
    icon: mdi:home-assistant
    panel: false
    badges: []
    cards:
      - type: entities
        show_header_toggle: false
        state_color: true
        entities:
          - type: custom:slider-entity-row
            entity: light.parlor_shelve_light
            toggle: true
            hide_when_off: true
          - type: custom:slider-entity-row
            entity: light.stairs_led
            toggle: true
            hide_when_off: true
          - type: custom:slider-entity-row
            entity: light.bathroom
            toggle: true
            hide_when_off: true
          - entity: switch.tv
            tab_action:
              action: toggle
          - entity: switch.printer
            tab_action:
              action: call-service
              service: switch.toggle
              service_data:
                entity: switch.printer
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            entity: light.all_lights
            name: Lights Off
            icon_height: 80px
            tap_action:
              action: call-service
              service: light.turn_off
              service_data:
                entity_id: light.all_lights
              confirmation:
                text: Do you really want to turn off all lights?
          - type: custom:button-card
            entity: input_select.daytime
            name: State Night
            icon: mdi:sleep
            icon_height: 80px
            tap_action:
              action: call-service
              service: input_select.select_option
              service_data:
                option: Night
              confirmation:
                text: |
                  Do you really want to set the day state to "Night"?

                  This turns lights and switches off!
          - type: custom:button-card
            entity: script.bathroom_demo
            name: Bathroom Demo
            icon_height: 80px
            tap_action:
              action: call-service
              service: script.bathroom_demo
              confirmation:
                text: Are you sure you want to run the bathroom demo?
  - icon: mdi:blinds
    title: Blinds
    path: blinds
    panel: true
    badges: []
    cards: []
  - title: Status
    path: status
    icon: mdi:information
    panel: true
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: glance
                state_color: true
                columns: 1
                entities:
                  - entity: person.christian_schwarzgruber
              - type: custom:button-card
                entity: input_boolean.presence
                name: Presence
                show_state: true
                icon_height: 25px
                styles:
                  card:
                    - height: 100px
                tap_action:
                  action: call-service
                  service: input_boolean.toggle
                  service_data:
                    entity_id: input_boolean.presence
                  confirmation:
                    text: Toggle presence?
              - type: glance
                state_color: true
                columns: 1
                entities:
                  - entity: person.sonia_avramidis
          - type: weather-forecast
            entity: weather.home
          - type: glance
            state_color: true
            columns: 3
            entities:
              - entity: input_boolean.presence
              - entity: input_select.daytime
              - entity: sensor.daylight
              - entity: binary_sensor.workday_sensor
              - entity: sun.sun
              - entity: binary_sensor.bedroom_motion
          - type: custom:battery-state-card
            entities:
              - entity: sensor.tablet_battery_level
                name: Tablet Battery
              - entity: sensor.bedroom_motion_battery_level
                name: Bedroom Motion Battery
              - entity: sensor.bath_switch_battery_level
                name: Bath Switch Battery
          - type: custom:mini-graph-card
            hours_to_show: 240
            name: Covid Status Austria
            points_per_hour: 0.10
            entities:
              - entity: sensor.austria_coronavirus_confirmed
                show_state: false
                show_fill: false
                name: Confirmed
              - entity: sensor.austria_coronavirus_recovered
                show_state: true
                show_fill: false
                name: Recovered
              - entity: sensor.austria_coronavirus_current
                show_state: true
                show_fill: false
                name: Current
              - entity: sensor.austria_coronavirus_deaths
                show_state: true
                show_fill: false
                name: Deaths
