- id: '1608464943573'
  alias: New Automation
  description: ''
  trigger:
  - platform: time
    at: '13:08:00'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.now.hour == 13 }}'
      sequence:
      - service: notify.persistent_notification
        data:
          message: '{{ trigger.now.hour }}:{{ trigger.now.minute }}:{{ trigger.now.second }}'
    default: []
  mode: single
