- id: '1602050820929'
  alias: Sun down lights
  description: Turn on lights when the sun goes down
  trigger:
  - platform: state
    entity_id: sensor.daylight
    to: sunset_start
  condition:
  - condition: state
    entity_id: input_boolean.presence
    state: 'on'
  action:
  - choose:
    - conditions:
      - condition: device
        type: is_off
        device_id: 03baa6e6081411eb958e6b58c8805747
        entity_id: light.stairs_led
        domain: light
      sequence:
      - service: scene.apply
        data:
          entities:
            light.stairs_led:
              min_mireds: 153
              max_mireds: 500
              effect_list:
              - colorloop
              brightness: 210
              color_temp: 375
              is_deconz_group: false
              friendly_name: Stairs LED-Stripe
              supported_features: 63
              state: 'on'
    default: []
  - choose:
    - conditions:
      - condition: device
        type: is_off
        device_id: 15f7180d0e0411eb814e538c319c793d
        entity_id: light.parlor_shelve_light
        domain: light
      sequence:
      - service: scene.apply
        data:
          entities:
            light.parlor_shelve_light:
              min_mireds: 140
              max_mireds: 600
              effect_list:
              - colorloop
              brightness: 180
              color_temp: 375
              is_deconz_group: false
              friendly_name: Parlor Shelve Light
              supported_features: 43
              state: 'on'
    default: []
  - choose:
    - conditions:
      - condition: device
        type: is_off
        device_id: 064385de065911eb86921ff8f4822c34
        entity_id: light.office_led
        domain: light
      - condition: state
        entity_id: switch.desk
        state: 'on'
      sequence:
      - service: scene.apply
        data:
          entities:
            light.office_led:
              min_mireds: 153
              max_mireds: 500
              effect_list:
              - colorloop
              brightness: 210
              color_temp: 375
              is_deconz_group: false
              friendly_name: Desk LED-Stripe
              supported_features: 63
              state: 'on'
    default: []
  mode: single
- id: '1602050996708'
  alias: Turn on stairs LED in the morning
  description: ''
  trigger:
  - platform: time
    at: 06:50:00
  condition:
  - condition: and
    conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.daylight
        state: sunrise_start
      - condition: state
        entity_id: sensor.daylight
        state: sunrise_end
      - condition: state
        entity_id: sensor.daylight
        state: dawn
    - condition: state
      state: 'on'
      entity_id: input_boolean.presence
    - condition: state
      entity_id: input_select.daytime
      state: Morning
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
  - scene: scene.stairs_morning_light
  mode: single
- id: '1602059477289'
  alias: Turn off stairs LED when daylight == true
  description: ''
  trigger:
  - platform: template
    value_template: '{{ state_attr(''sensor.daylight'', ''daylight'') }}'
  condition: []
  action:
  - type: turn_off
    device_id: 03baa6e6081411eb958e6b58c8805747
    entity_id: light.stairs_led
    domain: light
  - service: input_select.select_option
    entity_id: input_select.daytime
    data:
      option: Daytimes
  mode: single
- id: '1602353922519'
  alias: Night toilet light
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: d6016e8c8c59fbd93b03136917a223b4
    entity_id: binary_sensor.bedroom_motion
    domain: binary_sensor
  condition:
  - condition: template
    value_template: '{{ not state_attr(''sensor.daylight'', ''daylight'') }}'
  - condition: state
    entity_id: input_select.daytime
    state: Night
  - condition: device
    type: is_off
    device_id: 03baa6e6081411eb958e6b58c8805747
    entity_id: light.stairs_led
    domain: light
  action:
  - service: scene.turn_on
    data: {}
    entity_id: scene.night_toilet
  - delay: 00:00:30
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: device
          type: is_on
          device_id: 03baa6e6081411eb958e6b58c8805747
          entity_id: light.stairs_led
          domain: light
        - condition: template
          value_template: '{{ state_attr(''light.stairs_led'', ''brightness'') and
            state_attr(''light.stairs_led'', ''brightness'') <= 14 and state_attr(''light.stairs_led'',
            ''color_temp'') and state_attr(''light.stairs_led'', ''color_temp'') ==
            495 }}'
      sequence:
      - type: turn_on
        device_id: 03baa6e6081411eb958e6b58c8805747
        entity_id: light.stairs_led
        domain: light
        brightness_pct: 3
      - delay: 00:00:30
    default: []
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: device
          type: is_on
          device_id: 03baa6e6081411eb958e6b58c8805747
          entity_id: light.stairs_led
          domain: light
        - condition: template
          value_template: '{{ state_attr(''light.stairs_led'', ''brightness'') and
            state_attr(''light.stairs_led'', ''brightness'') <= 8 and state_attr(''light.stairs_led'',
            ''color_temp'') and state_attr(''light.stairs_led'', ''color_temp'') ==
            495 }}'
      sequence:
      - type: turn_on
        device_id: 03baa6e6081411eb958e6b58c8805747
        entity_id: light.stairs_led
        domain: light
        brightness_pct: 2
      - delay: 00:01:00
    default: []
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: device
          type: is_on
          device_id: 03baa6e6081411eb958e6b58c8805747
          entity_id: light.stairs_led
          domain: light
        - condition: template
          value_template: '{{ state_attr(''light.stairs_led'', ''brightness'') and
            state_attr(''light.stairs_led'', ''brightness'') <= 6 and state_attr(''light.stairs_led'',
            ''color_temp'') and state_attr(''light.stairs_led'', ''color_temp'') ==
            495 }}'
      sequence:
      - type: turn_on
        device_id: 03baa6e6081411eb958e6b58c8805747
        entity_id: light.stairs_led
        domain: light
        brightness_pct: 1
      - delay: 00:01:00
    default: []
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: device
          type: is_on
          device_id: 03baa6e6081411eb958e6b58c8805747
          entity_id: light.stairs_led
          domain: light
        - condition: template
          value_template: '{{ state_attr(''light.stairs_led'', ''brightness'') and
            state_attr(''light.stairs_led'', ''brightness'') <= 3 and state_attr(''light.stairs_led'',
            ''color_temp'') and state_attr(''light.stairs_led'', ''color_temp'') ==
            495 }}'
      sequence:
      - type: turn_off
        device_id: 03baa6e6081411eb958e6b58c8805747
        entity_id: light.stairs_led
        domain: light
    default: []
  mode: single
- id: '1603389408650'
  alias: Set daytime
  description: ''
  trigger:
  - platform: time
    at: 06:45:00
  - platform: time
    at: '18:00:00'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: time
        before: 06:50:00
        after: 06:44:00
      sequence:
      - service: input_select.select_option
        entity_id: input_select.daytime
        data:
          option: Morning
    default: []
  - choose:
    - conditions:
      - condition: time
        before: '18:05:00'
        after: '17:55:00'
      sequence:
      - service: input_select.select_option
        entity_id: input_select.daytime
        data:
          option: Evening
    default: []
  mode: single
- id: '1603390848183'
  alias: Night mode
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.daytime
    to: Night
  condition: []
  action:
  - service: homeassistant.turn_off
    data:
      entity_id: group.switches_and_lights
    entity_id: group.switches_and_lights
  - service: automation.trigger
    data: {}
    entity_id: automation.night_toilet_light
  mode: single
- id: '1603633705234'
  alias: Tablet battery warning
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.tablet_battery_level'')|int < 10 }}'
  condition:
  - condition: state
    entity_id: binary_sensor.tablet_is_charging
    state: 'off'
  action:
  - service: persistent_notification.create
    data:
      message: The tablet battery level has dropped below 10 %, please recharge!
      title: Critical Battery Level {{ states('sensor.tablet_battery_level') }} %
  mode: single
- id: '1603909632409'
  alias: Turn on lights in lower kitchen
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: a22002cc0fddfe438687ff5a86b3fd3b
    entity_id: binary_sensor.lower_kitchen_motion
    domain: binary_sensor
  condition:
  - condition: template
    value_template: '{{ states(''sensor.lower_kitchen_motion_lightlevel'')|float <
      30.0 }}'
  action:
  - domain: light
    entity_id: light.lower_kitchen
    device_id: 99c4272d194811eb9a33c1747a3f77e4
    type: turn_on
    brightness_pct: 55
  mode: single
- id: '1604071027469'
  alias: Turn on lights in front floor
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: d362c802f675d2a59d2080b94ebef8e4
    entity_id: binary_sensor.front_floor_motion
    domain: binary_sensor
  condition:
  - condition: template
    value_template: '{{ states(''sensor.front_floor_motion_lightlevel'')|float < 30.0
      }}'
  action:
  - type: turn_on
    device_id: 9a999d4e84bd4c8eb7c7779363b97b26
    entity_id: light.front_floor
    domain: light
    brightness_pct: 70
  mode: single
- id: '1604075158600'
  alias: Turn off lights in front floor
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: d362c802f675d2a59d2080b94ebef8e4
    entity_id: binary_sensor.front_floor_motion
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 20
  condition: []
  action:
  - type: turn_off
    device_id: 9a999d4e84bd4c8eb7c7779363b97b26
    entity_id: light.front_floor
    domain: light
  mode: single
- id: '1604075563242'
  alias: Turn off lights in lower kitchen
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: a22002cc0fddfe438687ff5a86b3fd3b
    entity_id: binary_sensor.lower_kitchen_motion
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 20
  condition: []
  action:
  - type: turn_off
    device_id: 99c4272d194811eb9a33c1747a3f77e4
    entity_id: light.lower_kitchen
    domain: light
  mode: single
