- platform: mqtt
  name: Heating
  icon: mdi:home-thermometer
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: true
  payload_off: false
  availability_topic: "heating/tele/LWT"
  temperature_command_topic: "heating/thermostat/set/targetTemperature"
  temperature_state_topic: "heating/stat/things/thermostat/properties"
  temperature_state_template: "{{ value_json.targetTemperature }}"
  current_temperature_topic: "heating/stat/things/thermostat/properties"
  current_temperature_template: "{{ value_json.temperature }}"
  mode_command_topic: "heating/thermostat/set/mode"
  mode_state_topic: "heating/stat/things/thermostat/properties"
  mode_state_template: "{{ value_json.mode }}"
  modes: [ "heat", "auto", "off" ]
  action_topic: "heating/stat/things/thermostat/properties"
  action_template: "{{ value_json.action }}"
  min_temp: 5
  max_temp: 35
  temp_step: 0.5
  precision: 0.5
