# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

wake_on_lan:

# Text to speech
tts:
  - platform: google_translate

binary_sensor:
  - platform: workday
    country: DE



# Nextcloud
#nextcloud:
#    url: https://cloud.casch.at
#    username: chrisluxtux
#    password:



# logger:
#   default: info
#   logs:
#     homeassistant.core: debug
#     homeassistant.components.zha: debug
#     bellows.zigbee.application: debug
#     bellows.ezsp: debug
#     zigpy: debug
#     zigpy_cc: debug
#     zigpy_deconz.zigbee.application: debug
#     zigpy_deconz.api: debug
#     zigpy_xbee.zigbee.application: debug
#     zigpy_xbee.api: debug
#     zigpy_zigate: debug
#     zigpy_znp: debug
#     zhaquirks: debug



switch: !include switch.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
