# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# https://www.home-assistant.io/integrations/http
http:
  server_host: !secret server_host
  server_port: !secret server_port
  cors_allowed_origins:
    - https://ha.casch.at
    - https://homeassistant.casch.at
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret server_ip
    - 172.30.33.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5

# https://www.home-assistant.io/integrations/logger/
# logger:
#  default: info # defaults to warning
#  logs:
#     pydeconz: debug
#     homeassistant.core: debug
#     homeassistant.components.deconz: debug

# https://www.home-assistant.io/integrations/recorder
recorder:
  purge_keep_days: 2
  commit_interval: 10

# https://www.home-assistant.io/integrations/logbook/
logbook:
  exclude:
    entity_globs:
      - sensor.date_time_*
    # entities:
    #   - binary_sensor.c200_camera_motion_detection

homeassistant:
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /tmp

frontend:
  themes: !include_dir_merge_named themes

# Enable WOL integration -> https://www.home-assistant.io/integrations/wake_on_lan
wake_on_lan:

# Text to speech
tts:
  - platform: google_translate

# stream:

# For onvif integration?
# ffmpeg:

# Shell commands
shell_command:
  # Need to specify IP (resolve doesn't work :-?),
  turn_off_server: !secret server_off

automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
light: !include lights.yaml
lovelace: !include lovelace/lovelace.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switch.yaml
template: !include templates.yaml

calendar:
  - platform: caldav
    url: !secret nextcloud_webdav_url
    username: !secret nextcloud_user
    password: !secret nextcloud_password
    custom_calendars:
      - name: Holiday
        calendar: Work
        search: "^Schwarzgruber_(UR|GT)"
      - name: Home Office
        calendar: Work
        search: "^Schwarzgruber_HO"

# https://www.home-assistant.io/integrations/influxdb
influxdb: !include influxdb.yaml
mqtt: !include mqtt.yaml
