# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes

# Enable WOL integration
wake_on_lan:

# Text to speech
tts:
  - platform: google_translate

binary_sensor:
  - platform: workday
    country: AT

# Shell commands
shell_command:
  # Need to specify IP (resolve doesn't work :-?),
  turn_off_tower: !secret tower_off

device_tracker:
  - platform: ping
    hosts:
      huawei_p20_router: 192.168.1.15
      galaxy_a2_router: 192.168.1.7
      lap_02_lan_router: 192.168.1.18
      lap_02_wlan_router: 192.168.1.19
      work_wlan_router: 192.168.1.11
      tower_wlan_router: 192.168.1.17
    # interval_seconds: 30        # default 12
    count: 3
    consider_home: 120

sensor: !include sensors.yaml
lovelace: !include lovelace/lovelace.yaml
switch: !include switch.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
scene: !include scenes.yaml


# Nextcloud
#nextcloud:
#    url: https://cloud.casch.at
#    username: chrisluxtux
#    password:



# logger:
#   default: info
#   logs:
#     pydeconz: debug
#     homeassistant.core: debug
#     homeassistant.components.deconz: debug
