# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# https://www.home-assistant.io/integrations/logger/
# logger:
#  default: info # defaults to warning
#  logs:
#     pydeconz: debug
#     homeassistant.core: debug
#     homeassistant.components.deconz: debug

# https://www.home-assistant.io/integrations/recorder
recorder:
  purge_keep_days: 2
  commit_interval: 10

# https://www.home-assistant.io/integrations/logbook/
logbook:
  exclude:
    entity_globs:
      - sensor.date_time_*
    # entities:
    #   - binary_sensor.c200_camera_motion_detection

homeassistant:
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /tmp

frontend:
  themes: !include_dir_merge_named themes

apcupsd:
  host: 192.168.1.29

# Enable WOL integration
wake_on_lan:

# Text to speech
tts:
  - platform: google_translate

# stream:

# For onvif integration?
# ffmpeg:

# Shell commands
shell_command:
  # Need to specify IP (resolve doesn't work :-?),
  turn_off_tower: !secret tower_off

sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
lovelace: !include lovelace/lovelace.yaml
switch: !include switch.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml
cover: !include covers.yaml

calendar:
  - platform: caldav
    url: !secret nextcloud_webdav_url
    username: !secret nextcloud_user
    password: !secret nextcloud_password
    custom_calendars:
      - name: Holiday
        calendar: Work
        search: '^Schwarzgruber_(UR|GT)'
      - name: Home Office
        calendar: Work
        search: '^Schwarzgruber_HO'

# https://www.home-assistant.io/integrations/influxdb
influxdb: !include influxdb.yaml


