# Configure a default setup of Home Assistant (frontend, api, etc)
# https://github.com/home-assistant/core/blob/dev/homeassistant/components/default_config/manifest.json#L5
# Don't want to use all of them, therefore I needed to remove "default_config:" and enable just the other ones
application_credentials:
bluetooth:
# cloud:
counter:
dhcp:
# energy:
hardware:
history:
homeassistant_alerts:
input_button:
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
# map:
media_source:
mobile_app:
my:
network:
person:
schedule:
ssdp:
sun:
system_health:
# tag:
timer:
usb:
webhook:
zeroconf:
# zon:

# https://www.home-assistant.io/integrations/http
http:
  #server_host: 0.0.0.0
  server_port: 8123
  cors_allowed_origins:
    - https://ha.casch.at
    - https://homeassistant.casch.at
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret server_ip
    - 172.30.33.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5


# https://www.home-assistant.io/integrations/logger/
logger:
  default: info # defaults to warning
#  logs:
#     pydeconz: debug
#     homeassistant.core: debug
#     homeassistant.components.deconz: debug

# https://www.home-assistant.io/integrations/recorder
recorder:
  purge_keep_days: 14
  commit_interval: 5

# https://www.home-assistant.io/integrations/logbook/
logbook:
  exclude:
    entity_globs:
      - sensor.date_time_*
    # entities:
    #   - binary_sensor.c200_camera_motion_detection

homeassistant:
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /tmp
  media_dirs:
    local: /media/casch/local
    recording: /media/casch/recordings

frontend:
  themes: !include_dir_merge_named themes

# Enable WOL integration -> https://www.home-assistant.io/integrations/wake_on_lan
wake_on_lan:

# Text to speech
tts:
  - platform: google_translate

# stream:

# For onvif integration?
# ffmpeg:

# Shell commands
shell_command:
  # Need to specify IP (resolve doesn't work :-?),
  turn_off_server: !secret server_off

automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
# light: !include lights.yaml
lovelace: !include lovelace/lovelace.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switch.yaml
template: !include templates.yaml
notify: !include notify.yaml

calendar:
  - platform: caldav
    url: !secret nextcloud_webdav_url
    username: !secret nextcloud_user
    password: !secret nextcloud_password
    custom_calendars:
      - name: Holiday
        calendar: Work
        search: "^Schwarzgruber_(UR|GT)"
      - name: Home Office
        calendar: Work
        search: "^Schwarzgruber_HO"

# https://www.home-assistant.io/integrations/influxdb
influxdb: !include influxdb.yaml
mqtt: !include mqtt.yaml
