# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Enable python scripts
python_script:

# Enable themes
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
    - /hacsfiles/lovelace-paper-buttons-row/paper-buttons-row.js
    - /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    - /hacsfiles/rgb-light-card/card.js
    - /hacsfiles/mini-humidifier/mini-humidifier-bundle.js
    # - /hacsfiles/vacuum-card/vacuum-card.js
    - /hacsfiles/battery-state-card/battery-state-card.js

# Enable WOL integration
wake_on_lan:

# Text to speech
tts:
  - platform: google_translate

binary_sensor:
  - platform: workday
    country: DE

# Shell commands
shell_command:
  # Need specify IP (resolve doesn't work :-?),
  turn_off_tower: ssh -i /config/ssh/id_rsa root@192.168.1.17 systemctl poweroff

switch: !include switch.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


# Nextcloud
#nextcloud:
#    url: https://cloud.casch.at
#    username: chrisluxtux
#    password:



# logger:
#   default: info
#   logs:
#     homeassistant.core: debug
#     homeassistant.components.zha: debug
#     bellows.zigbee.application: debug
#     bellows.ezsp: debug
#     zigpy: debug
#     zigpy_cc: debug
#     zigpy_deconz.zigbee.application: debug
#     zigpy_deconz.api: debug
#     zigpy_xbee.zigbee.application: debug
#     zigpy_xbee.api: debug
#     zigpy_zigate: debug
#     zigpy_znp: debug
#     zhaquirks: debug
