# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /tmp

frontend:
  themes: !include_dir_merge_named themes

# Enable WOL integration
wake_on_lan:

# Text to speech
tts:
  - platform: google_translate

binary_sensor:
  - platform: workday
    country: AT

# stream:

# For onvif integration?
# ffmpeg:

# Shell commands
shell_command:
  # Need to specify IP (resolve doesn't work :-?),
  turn_off_tower: !secret tower_off

device_tracker:
  - platform: ping
    hosts:
      huawei_p20_router: 192.168.1.15
      galaxy_a2_router: 192.168.1.7
      lap_02_lan_router: 192.168.1.18
      lap_02_wlan_router: 192.168.1.19
      work_wlan_router: 192.168.1.11
      tower_lan_router: 192.168.1.17
    count: 3
    consider_home: 800

sensor: !include sensors.yaml
lovelace: !include lovelace/lovelace.yaml
switch: !include switch.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
scene: !include scenes.yaml

calendar:
  - platform: caldav
    url: !secret nextcloud_webdav_url
    username: !secret nextcloud_user
    password: !secret nextcloud_password
    custom_calendars:
      - name: Holiday
        calendar: Work
        search: '^Schwarzgruber_(UR|GT)'
      - name: Home Office
        calendar: Work
        search: '^Schwarzgruber_HO'

# logger:
#   default: info
#   logs:
#     pydeconz: debug
#     homeassistant.core: debug
#     homeassistant.components.deconz: debug
