- platform: mqtt
  name: "Aroma Diffuser Light"
  unique_id: "aroma_diffuser_light_01"
  command_topic: "cmnd/aroma_diffuser/EVENT"
  state_topic: "tele/aroma_diffuser/STATE"
  state_value_template: >-
    {% if value_json.Light is defined %}
      {{ value_json.Light }}
    {% endif %}
  # brightness_command_topic: "cmnd/aroma_diffuser/DIMMER"
  # brightness_state_topic: "tele/aroma_diffuser/STATE"
  # brightness_scale: 100
  # brightness_value_template: 100
  effect_command_topic: "cmnd/aroma_diffuser/EVENT"
  effect_state_topic: "tele/aroma_diffuser/STATE"
  effect_value_template: >-
    {% if value_json.Light is defined %}
      {{ value_json.LightMode }}
    {% endif %}
  effect_list:
    - rgb_cycle
    - color
  availability_topic: "tele/aroma_diffuser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: true
  rgb_command_topic: "cmnd/aroma_diffuser/TUYASEND3"
  rgb_command_template: >-
    {% set brightness = 100 %}
    {{ '8,%02x%02x%02x003cff64' | format(red, green, blue) }}
  rgb_value_template: >-
    {% if value_json.TuyaReceived is defined and '8' in value_json['TuyaReceived'] %}
      {{
        (value_json['TuyaReceived']['8'].Type3Data[0:2]|int(base=16),value_json['TuyaReceived']['8'].Type3Data[2:4]|int(base=16),value_json['TuyaReceived']['8'].Type3Data[4:6]|int(base=16)) | join(',')
      }}
    {% endif %}
  rgb_state_topic: "tele/aroma_diffuser/RESULT"
