- platform: group
  name: Nightstand Lights
  entities:
    - light.nightstand_christian_light
    - light.nightstand_partner_light

- platform: group
  name: Bathroom Lights
  entities:
    - light.bathroom_back_left_light
    - light.bathroom_lamp_light
    - light.bathroom_mirror_light_switch

- platform: group
  name: Bathroom Mirror Ceiling Lights
  entities:
    - light.bathroom_back_left_light
    - light.bathroom_mirror_light_switch

- platform: group
  name: Office Lights
  entities:
    - light.office_back_light
    - light.office_desk_light
    - light.office_front_light

- platform: group
  name: Office Ceiling Lights
  entities:
    - light.office_back_light
    - light.office_front_light

- platform: group
  name: All Lights
  entities:
    - light.all_zigbee_lights
    - light.bathroom_lights
    - light.nightstand_lights
    - light.office_ceiling_lights
    - light.upstairs_lamp_light
    - light.panel_mirror_switch
    - light.kitchen_cabinet_switch
