# - platform: rpi_rf
#   gpio: 17
#   switches:
#     # TV: # 5
#     #   code_on: 5534979 # (S)FF F0 F1 FF 00 01 -> 0101 0100 0111 0101 0000 0011
#     #   code_off: 5534988 # (S)FF F0 F1 FF 00 10 -> 0101 0100 0111 0101 0000 1100
#     #   pulselength: 165
#     #   signal_repetitions: 15
#     Printer: # 4
#                                                  0101 0100 0101 1101 0000 0011
#       code_on: 5528835 # (S)FF F0 FF 1F 00 01 -> 0101 0100 0101 1101 0000 0011
#                                                   0101 0100 0101 1101 0000 1100
#       code_off: 5528844 # (S)FF F0 FF 1F 00 10 -> 0101 0100 0101 1101 0000 1100
#       pulselength: 165
#       signal_repetitions: 15
#     # Desk: # 3
#     #   code_on: 5527299 # (S)FF F0 FF F1 00 01 -> 0101 0100 0101 0111 0000 0011
#     #   code_off: 5527308 # (S)FF F0 FF F1 00 10 -> 0101 0100 0101 0111 0000 1100
#     #   pulselength: 165
#     #   signal_repetitions: 10
#     Tower: # 2
#       code_on: 5526979 # (S)FF F0 FF FF 10 01 -> 0101 0100 0101 0101 1100 0011
#       code_off: 5526988 # (S)FF F0 FF FF 10 10 -> 0101 0100 0101 0101 1100 1100
#       pulselength: 165
#       signal_repetitions: 10
#     # Laptop: # 1
#     #   code_on: 5526835 # (S)FF F0 FF FF 01 01 -> 0101 0100 0101 0101 0011 0011
#     #   code_off: 5526844 # (S)FF F0 FF FF 01 10 -> 0101 0100 0101 0101 0011 1100
#     #   pulselength: 165
#     #   signal_repetitions: 10

- platform: wake_on_lan
  mac: !secret server_mac
  name: wake_on_lan_server
  host: !secret server_ip
  broadcast_address: !secret broadcast_address
  turn_off:
    service: shell_command.turn_off_server

# - platform: wake_on_lan
#   mac: !secret server_mac
#   name: wake_on_lan_realtek_server
#   host: !secret server_ip
#   broadcast_address: !secret broadcast_address
#   turn_off:
#     service: shell_command.turn_off_server

# - platform: wake_on_lan
#   mac: !secret server_mac
#   name: wake_on_lan_intel_server
#   host: !secret server_ip
#   broadcast_address: !secret broadcast_address
#   turn_off:
#     service: shell_command.turn_off_server

- platform: wake_on_lan
  mac: !secret tower_mac
  name: wake_on_lan_tower
  host: !secret tower_ip
  broadcast_address: !secret broadcast_address
  # turn_off:
  #   service: shell_command.turn_off_tower

- platform: group
  unique_id: deskt_and_laptop_group
  name: Desk and Laptop Group
  entities:
    - switch.desk_switch
    - switch.laptop_switch

- platform: group
  unique_id: switches_group
  name: Switches Group
  entities:
    - switch.desk_switch
    - switch.laptop_switch
    - switch.printer_switch
    - switch.3d_printer_switch

# - platform: group
#   unique_id: bedroom_group
#   name: Bedroom Group
#   # icon: mdi:bed
#   entities:
#     - switch.nightstand_switch

- platform: group
  unique_id: devices_group
  name: Devices Group
  entities:
    - switch.aroma_diffuser

- platform: group
  unique_id: shutters_up_group
  name: Shutters Up Group
  entities:
    - switch.bedroom_shutter_up_relay
    - switch.parlor_shutter_up_relay

- platform: group
  unique_id: shutters_down_group
  name: Shutters Down Group
  entities:
    - switch.bedroom_shutter_down_relay
    - switch.parlor_shutter_down_relay
