title: Home
icon: mdi:home-assistant
views:
  - path: default_view
    title: Switches
    panel: false
    icon: mdi:dip-switch
    badges: []
    cards:
      - type: entities
        title: Switches
        show_header_toggle: false
        state_color: true
        entities:
          - entity: switch.desk
            icon: mdi:desk
          - entity: switch.laptop
            icon: mdi:laptop
          - entity: switch.printer
            icon: mdi:printer
          - entity: switch.nightstand
            icon: mdi:floor-lamp
          - entity: switch.tower
            icon: mdi:desktop-tower
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                entity: switch.laptop
                icon: mdi:laptop
                icon_height: 80px
                triggers_update:
                  - switch.desk
                tap_action:
                  action: call-service
                  service: script.desk_and_laptop_on
              - type: custom:button-card
                entity: group.switches
                name: Switches Off
                icon_height: 80px
                tap_action:
                  action: call-service
                  service: homeassistant.turn_off
                  service_data:
                    entity_id: group.switches
                  confirmation:
                    text: Do you really want to turn all switches off?
              - type: custom:button-card
                entity: group.switches_and_lights
                name: Switches/Lights Off
                icon_height: 80px
                tap_action:
                  action: call-service
                  service: homeassistant.turn_off
                  service_data:
                    entity_id: group.switches_and_lights
                  confirmation:
                    text: Do you really want to turn all switches and lights off?
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                entity: script.wake_tower
                icon_height: 80px
                tap_action:
                  action: call-service
                  service: script.wake_tower
                  confirmation:
                    text: Do you really want to wake the Tower?
              - type: custom:button-card
                entity: switch.tower
                icon: hass:desktop-tower
                name: Tower Off
                tap_action:
                  action: call-service
                  service: script.tower_off
                  confirmation:
                    text: Do you really want to turn off the Tower?
                icon_height: 80px
              - type: custom:button-card
                entity: input_select.daytime
                name: State Night
                icon: mdi:sleep
                icon_height: 80px
                state:
                  - value: 'Night'
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.daytime
                    option: Night
                  confirmation:
                    text: |
                      Do you really want to set the day state to "Night"?

                      This turns all lights and switches off!
  - title: Lights
    path: lights
    panel: false
    icon: mdi:lightbulb-group
    badges: []
    cards:
      - type: entities
        title: Stripes (RGB)
        entities:
          - type: custom:slider-entity-row
            entity: light.led_stripes
            toggle: true
            hide_when_off: true
            name: All
          - type: custom:slider-entity-row
            entity: light.stairs_led
            toggle: true
            hide_when_off: true
            name: Stairs
          - type: custom:slider-entity-row
            entity: light.office_led
            toggle: true
            hide_when_off: true
            name: Office
      - type: entities
        title: Parlor
        entities:
          - type: custom:slider-entity-row
            entity: light.parlor
            toggle: true
            hide_when_off: true
            name: All
          - type: custom:slider-entity-row
            entity: light.parlor_shelve_light
            name: Shelve
            toggle: true
            hide_when_off: true
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                entity: scene.bathroom_bath
                name: Bath Warm
                icon: mdi:hot-tub
                icon_height: 50px
                styles:
                  icon:
                    - color: "#FFA69E"
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.bathroom_bath
              - type: custom:button-card
                entity: scene.bathroom_morning
                name: Bath Cold
                icon: mdi:shower
                icon_height: 50px
                styles:
                  icon:
                    - color: "#3D48FF"
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.bathroom_morning
              - type: custom:button-card
                entity: scene.chill
                icon: mdi:palette
                icon_height: 50px
                styles:
                  icon:
                    - color: "#0BC129"
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.chill
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                entity: scene.love
                icon_height: 50px
                styles:
                  icon:
                    - color: "#C10B0B"
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.love
              - type: custom:button-card
                entity: light.all_lights
                name: Lights Off
                icon_height: 50px
                tap_action:
                  action: call-service
                  service: homeassistant.turn_off
                  service_data:
                    entity_id: group.all_lights_extra
                  confirmation:
                    text: Do you really want to turn off all lights?
              - type: custom:button-card
                entity: scene.night
                icon_height: 50px
                styles:
                  icon:
                    - color: "#FFE59E"
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.night
      - type: entities
        title: Lower Kitchen
        entities:
          - type: custom:slider-entity-row
            entity: light.lower_kitchen
            toggle: true
            hide_when_off: true
            name: All
          - type: custom:slider-entity-row
            entity: light.lower_kitchen_back
            name: Back
            toggle: true
            hide_when_off: true
          - type: custom:slider-entity-row
            entity: light.lower_kitchen_front
            name: Front
            toggle: true
            hide_when_off: true
      - type: entities
        title: Bathroom
        entities:
          - type: custom:slider-entity-row
            entity: light.bathroom
            toggle: true
            hide_when_off: true
            name: All
          - type: custom:slider-entity-row
            entity: light.bathroom_front_left
            name: Left Front
            toggle: true
            hide_when_off: true
          - type: custom:slider-entity-row
            entity: light.bathroom_back_left
            name: Left Back
            toggle: true
            hide_when_off: true
          - type: custom:slider-entity-row
            entity: light.bathroom_back_right
            name: Right Back
            toggle: true
            hide_when_off: true
          - type: custom:slider-entity-row
            entity: light.bathroom_front_right
            name: Right Front
            toggle: true
            hide_when_off: true
  - title: Status
    path: status
    icon: mdi:information
    panel: true
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                color_type: blank-card
              - type: custom:button-card
                entity: person.christian_schwarzgruber
                show_entity_picture: true
                show_state: true
                styles:
                  card:
                    - background: rgba(0, 0, 0, 0)
                  entity_picture:
                    - border-radius: 50%
                    - -webkit-box-shadow: 0px 0px 3px 3px var(--button-card-light-color)
                    - box-shadow: 0px 0px 3px 3px var(--button-card-light-color)
                state_display: >
                  [[[
                    if (entity.state == "home")
                      return "is at home";
                    else if (entity.state == "not_home")
                      return "is away";
                    else
                      return "unknown";
                  ]]]
              - type: custom:button-card
                entity: person.sonia_avramidis
                show_entity_picture: true
                show_state: true
                styles:
                  card:
                    - background: rgba(0, 0, 0, 0)
                  entity_picture:
                    - border-radius: 50%
                    - -webkit-box-shadow: 0px 0px 3px 3px var(--button-card-light-color)
                    - box-shadow: 0px 0px 3px 3px var(--button-card-light-color)
                state_display: >
                  [[[
                    if (entity.state == "home")
                      return "is at home";
                    else if (entity.state == "not_home")
                      return "is away";
                    else
                      return "unknown";
                  ]]]
              - type: custom:button-card
                color_type: blank-card
          - type: weather-forecast
            entity: weather.home
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                entity: input_boolean.presence
                show_state: true
                styles:
                  card:
                    - height: 100px
              - type: custom:button-card
                entity: sun.sun
                show_state: true
                styles:
                  card:
                    - height: 100px
              - type: custom:button-card
                entity: sensor.daylight
                show_state: true
                name: Sun
                styles:
                  card:
                    - height: 100px
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                entity: binary_sensor.workday_sensor
                show_state: true
                styles:
                  card:
                    - height: 100px
              - type: custom:button-card
                entity: input_select.daytime
                show_state: true
                styles:
                  card:
                    - height: 100px
              - type: custom:button-card
                color_type: blank-card
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                entity: sensor.hacs
                name: HACS
                show_state: true
                icon: mdi:update
                styles:
                  card:
                    - height: 100px
              - type: custom:button-card
                name: Restart HA
                icon: mdi:restart
                icon_height: 50px
                styles:
                  card:
                    - height: 100px
                  icon:
                    - color: "#C10B0B"
                tap_action:
                  action: call-service
                  service: homeassistant.restart
                  confirmation:
                    text: Restart Home Assistant?
              - type: custom:button-card
                entity: binary_sensor.updater
                show_state: true
                icon: mdi:update
                styles:
                  card:
                    - height: 100px
          # - type: horizontal-stack
          #   cards:
          #     - type: custom:button-card
          #       color_type: blank-card
          #       styles:
          #         card:
          #           - height: 100px
          #     - type: custom:button-card
          #       color_type: blank-card
          #       styles:
          #         card:
          #           - height: 100px
          - type: custom:mini-graph-card
            entities:
              - entity: binary_sensor.bedroom_motion
                name: Bedroom
              - entity: binary_sensor.lower_kitchen_motion
                name: Lower Kitchen
            name: Bedroom motion (24h)
            hours_to_show: 24
            points_per_hour: 30
            aggregate_func: max
            line_width: 1
            smoothing: false
            state_map:
              - value: "off"
                label: Clear
              - value: "on"
                label: Detected
          - type: custom:mini-graph-card
            entities:
              - entity: sensor.lower_kitchen_motion_lightlevel
                name: Lower kitchen
              - entity: sensor.bedroom_motion_lightlevel
                name: Bedroom
            name: Motion sensors lightlevel (24h)
            hours_to_show: 24
            points_per_hour: 10
            line_width: 1
          - type: custom:battery-state-card
            title: Battery Level
            # secondary_info: last_updated
            sort_by_level: asc
            icon: mdi:battery-flash
            color_gradient:
              - '#FF0000'
              - '#FFFF00'
              - '#00FF00'
            entities:
              - entity: sensor.tablet_battery_level
                name: Tablet
                tap_action: more-info
                charging_state:
                  entity_id: binary_sensor.tablet_is_charging
                  state: "on"
                  icon: mdi:flash
                  color: yellow
              - entity: sensor.bedroom_motion_battery_level
                name: Bedroom motion sensor
                tap_action: more-info
              - entity: sensor.lower_kitchen_motion_battery_level
                name: Lower kitchen motion sensor
                tap_action: more-info
              - entity: sensor.bath_switch_battery_level
                name: Bath switch
                tap_action: more-info
            filter:
              include:
                - name: attributes.device_class
                  value: battery
              exclude:
                - name: state
                  value: 100
                  operator: ">"
          - type: custom:mini-graph-card
            hours_to_show: 2400
            name: Covid Status Austria
            points_per_hour: 0.0416666666667
            line_width: 2
            show:
              fill: false
            entities:
              - entity: sensor.austria_coronavirus_confirmed
                name: Confirmed
              - entity: sensor.austria_coronavirus_recovered
                name: Recovered
              - entity: sensor.austria_coronavirus_current
                name: Current
              - entity: sensor.austria_coronavirus_deaths
                name: Deaths
#066F22
#0FB72C
#0FFB0B
#F3F135
#F05F00
#C10B0B
