title: Home
icon: mdi:home-assistant
views:
  - path: default_view
    title: Switches
    panel: false
    icon: 'mdi:dip-switch'
    badges: []
    cards:
      - type: entities
        entities:
          - switch.desk
          - switch.laptop
          - switch.printer
          - switch.tv
          - switch.tower
        show_header_toggle: false
        title: Switches
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: button
                entity: script.desk_and_laptop_on
                tap_action:
                  action: call-service
                  service: script.desk_and_laptop_on
                icon_height: 80px
              - type: button
                entity: script.switches_off
                tap_action:
                  action: call-service
                  service: script.switches_off
                  confirmation:
                    text: Turn all switches off?
                icon_height: 80px
              - type: button
                entity: script.wake_tower
                tap_action:
                  action: call-service
                  service: script.wake_tower
                  confirmation:
                    text: Wake Tower?
                icon_height: 80px
          - type: horizontal-stack
            cards:
              - type: button
                entity: script.tower_off
                tap_action:
                  action: call-service
                  service: script.tower_off
                  confirmation:
                    text: Turn off Tower?
                icon_height: 80px
              - type: button
                entity: script.set_daytime_to_night
                tap_action:
                  action: call-service
                  service: script.set_daytime_to_night
                  confirmation:
                    text: |
                      Do you really want to set the day state to night?

                      This turns lights and switches off!
                name: State Night
                icon_height: 50px
              - type: button
                entity: script.lights_off
                tap_action:
                  action: call-service
                  service: script.lights_off
                  confirmation:
                    text: Are you sure you want to turn off all lights?
                name: Lights Off
                icon_height: 80px
  - title: Lights
    path: lights
    panel: false
    icon: 'mdi:lightbulb-group'
    badges: []
    cards:
      - type: entities
        title: Stripes (RGB)
        entities:
          - type: 'custom:slider-entity-row'
            entity: light.led_stripes
            toggle: true
            hide_when_off: true
            name: All
          - type: 'custom:slider-entity-row'
            entity: light.stairs_led
            toggle: true
            hide_when_off: true
            name: Stairs
          - type: 'custom:slider-entity-row'
            entity: light.office_led
            toggle: true
            hide_when_off: true
            name: Office
      - type: entities
        title: Parlor
        entities:
          - type: 'custom:slider-entity-row'
            entity: light.parlor
            toggle: true
            hide_when_off: true
            name: All
          - type: 'custom:slider-entity-row'
            entity: light.parlor_shelve_light
            name: Shelve Light
            toggle: true
            hide_when_off: true
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: button
                entity: scene.bathroom_bath
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.bathroom_bath
                name: Bath Warm
                icon: 'mdi:hot-tub'
                icon_height: 50px
              - type: button
                entity: scene.bathroom_morning
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.bathroom_morning
                name: Bath Cold
                icon: 'mdi:shower'
                icon_height: 50px
              - type: button
                entity: scene.chill
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.chill
                icon_height: 50px
          - type: horizontal-stack
            cards:
              - type: button
                entity: scene.love
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.love
                icon_height: 50px
              - type: button
                entity: scene.night
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.night
                icon_height: 50px
          - type: horizontal-stack
            cards:
              - type: button
                entity: script.lights_off
                tap_action:
                  action: call-service
                  service: script.lights_off
                  confirmation:
                    text: Are you sure you want to turn off all lights?
                name: Lights Off
                icon_height: 50px
      - type: entities
        title: Bathroom
        entities:
          - type: 'custom:slider-entity-row'
            entity: light.bathroom
            toggle: true
            hide_when_off: true
            name: All
          - type: 'custom:slider-entity-row'
            entity: light.bathroom_light_1
            name: Left Front
            toggle: true
            hide_when_off: true
          - type: 'custom:slider-entity-row'
            entity: light.bathroom_light_2
            name: Left Back
            toggle: true
            hide_when_off: true
          - type: 'custom:slider-entity-row'
            entity: light.bathroom_light_3
            name: Right Back
            toggle: true
            hide_when_off: true
          - type: 'custom:slider-entity-row'
            entity: light.bathroom_light_4
            name: Right Front
            toggle: true
            hide_when_off: true
  - title: Status
    path: status
    icon: 'mdi:information'
    panel: true
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: glance
                entities:
                  - entity: person.christian_schwarzgruber
                state_color: true
                columns: 1
              - type: button
                entity: input_boolean.presence
                name: Presence
                show_state: true
                icon_height: 50px
                tap_action:
                  action: call-service
                  service: input_boolean.toggle
                  confirmation:
                    text: Toggle presence?
              - type: glance
                entities:
                  - entity: person.sonia_avramidis
                state_color: true
                columns: 1
          - type: glance
            entities:
              - entity: input_select.daytime
              - entity: sensor.daylight
                name: Sun
              - entity: sun.sun
            state_color: true
            columns: 3
          - type: glance
            entities:
              - entity: binary_sensor.workday_sensor
                name: Workday
              - entity: binary_sensor.bedroom_motion
            state_color: true
            columns: 2
          - type: glance
            entities:
              - entity: sensor.hacs
                name: HACS
              - entity: binary_sensor.updater
            state_color: true
            columns: 2
          - type: horizontal-stack
            cards:
              - type: button
              - type: button
                name: Restart HA
                icon: 'mdi:restart'
                icon_height: 50px
                tap_action:
                  action: call-service
                  service: homeassistant.restart
                  confirmation:
                    text: Restart Home Assistant?
              - type: button
          - type: 'custom:battery-state-card'
            entities:
              - entity: sensor.tablet_battery_level
                name: Tablet Battery
              - entity: sensor.bedroom_motion_battery_level
                name: Bedroom Motion Battery
              - entity: sensor.bath_switch_battery_level
                name: Bath Switch Battery
