title: Home
icon: mdi:home-assistant
views:
  # I didn't use "!include_dir_list", because they wouldn't be in that order I like them
  - !include lovelace/view/switches.yaml
  - !include lovelace/view/lights.yaml
  - !include lovelace/view/shutter.yaml
  - !include lovelace/view/tv.yaml
  - !include lovelace/view/air_conditioner.yaml
  - !include lovelace/view/status.yaml

#066F22
#0FB72C
#0FFB0B
#F3F135
#F05F00
#C10B0B
