- alias: Home Office
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.daytime
    to: Morning
  - platform: state
    entity_id: person.christian_schwarzgruber
    to: home
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: state
    entity_id: input_boolean.presence
    state: 'on'
  - condition: time
    after: '00:06:45'
    before: '00:17:00'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.desk_switch
  - delay: 00:00:02
  - service: switch.turn_on
    data:
      entity_id: switch.laptop
  mode: single
