- alias: Office LED On/Off
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: ed75d33e4fdc486c13f061762e77931c
    entity_id: switch.desk_switch
    domain: switch
  - platform: device
    type: turned_on
    device_id: ed75d33e4fdc486c13f061762e77931c
    entity_id: switch.desk_switch
    domain: switch
  - type: illuminance
    platform: device
    device_id: d362c802f675d2a59d2080b94ebef8e4
    entity_id: sensor.front_floor_lightlevel
    domain: sensor
    below: 60
    for:
      hours: 0
      minutes: 10
      seconds: 0
  - type: illuminance
    platform: device
    device_id: d362c802f675d2a59d2080b94ebef8e4
    entity_id: sensor.front_floor_lightlevel
    domain: sensor
    above: 59
    for:
      hours: 0
      minutes: 10
      seconds: 0      
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ states(''sensor.front_floor_lightlevel'')|float < 60 }}'
      - condition: state
        entity_id: switch.desk_switch
        state: 'on'
      sequence:
      - service: scene.turn_on
        data:
          entity_id: scene.office_work_light
    default: []
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: or
          conditions:
          - condition: state
            entity_id: switch.desk_switch
            state: 'off'
          - condition: template
            value_template: '{{ states(''sensor.front_floor_lightlevel'')|float >= 60 }}'
        - condition: state
          entity_id: light.office_led
          state: 'on'
      sequence:
      - type: turn_off
        device_id: 064385de065911eb86921ff8f4822c34
        entity_id: light.office_led
        domain: light
    default: []
  mode: single
