- alias: Morning light
  description: ''
  trigger:
  - platform: time
    at: 06:50:00
  condition:
  - condition: and
    conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.daylight
        state: sunrise_start
      - condition: state
        entity_id: sensor.daylight
        state: sunrise_end
      - condition: state
        entity_id: sensor.daylight
        state: dawn
    - condition: state
      state: 'on'
      entity_id: input_boolean.presence
    - condition: state
      entity_id: input_select.daytime
      state: Morning
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
  - scene: scene.stairs_morning_light
  mode: single
- alias: Turn off stairs LED when daylight == true
  description: ''
  trigger:
  - type: illuminance
    platform: device
    device_id: d362c802f675d2a59d2080b94ebef8e4
    entity_id: sensor.front_floor_lightlevel
    domain: sensor
    above: 80
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.presence
    state: 'on'
  action:
  - type: turn_off
    device_id: 03baa6e6081411eb958e6b58c8805747
    entity_id: light.stairs_led
    domain: light
  - service: input_select.select_option
    data:
      option: Daytimes
    entity_id: input_select.daytime
  mode: single
