wifi:
  domain: .lan
  fast_connect: true
  networks:
    - id: wifi_default
      ssid: !secret ssid
      password: !secret wlan_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${ap_ssid}
    password: !secret ap_password

  # Optional manual IP
#   manual_ip:
#     static_ip: ${ip}
#     gateway: 192.168.1.1
#     subnet: 255.255.255.0
  # https://esphome.io/components/wifi.html#power-save-mode
  #power_save_mode: None

  # https://esphome.io/components/esphome.html#changing-esphome-node-name (Changing the name of the device)
  # use_address: desk_control.local
  # use_address: upstairs_ir_remote.local

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Vienna
    servers:
     - galaxy

preferences:
  flash_write_interval: 60min

captive_portal:

# Enable logging
logger:
  # level: NONE
  level: ERROR
  # level: WARN
  # level: INFO
  # level: DEBUG # Defaultd
  # level: VERBOSE
  # level: VERY_VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret wlan_password
