wifi:
  ssid: !secret ssid
  password: !secret wlan_password
  fast_connect: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${ap_ssid}
    password: !secret ap_password

captive_portal:

# Enable logging
logger:
  # level: NONE
  # level: ERROR
  # level: WARN
  # level: INFO
  level: DEBUG # Default
  # level: VERBOSE
  # level: VERY_VERBOSE

# Enable Home Assistant API
api:
  password: !secret wlan_password

ota:
  password: !secret wlan_password
