substitutions:
  name: bathroom-mirror-light-switch
  ap_ssid: Bathroom Mir... Fallback Hotspot
  ip: 192.168.1.36
  channel_1: Bathroom Mirror Light
  channel_2: Bathroom Mirror Light Unused
  max_power: "2000.0"
  max_temp: "70.0"

<<: !include .shelly-2.5-as-light-template.yaml
