substitutions:
  name: bathroom-mirror-light
  ap_ssid: Bath Mirror Light Fallb. Hotspot

esphome:
  <<: !include .board-config-az-delivery-devkit-v4.yaml

<<: !include .base-config.yaml


# https://esphome.io/components/light/index.html#config-light
light:
  - platform: cwww
    name: Bathroom Mirror Light
    cold_white: cold_white
    warm_white: warm_white
    cold_white_color_temperature: 6000K
    warm_white_color_temperature: 3000K
    # Reduce flickering when both channels are on -- to much power?
    constant_brightness: true
    default_transition_length: 0s
    gamma_correct: 0

# https://esphome.io/components/output/index.html
output:
  # https://esphome.io/components/output/ledc.html?highlight=ledc
  - platform: ledc
    pin: 33
    id: cold_white
    frequency: 9765Hz # 19531Hz, 39061Hz
    # decrease max power to prevend flickering
    max_power: 0.85
  - platform: ledc
    pin: 32
    id: warm_white
    frequency: 9765Hz # 19531Hz, 39061Hz
    # decrease max power to prevend flickering
    max_power: 0.85
