substitutions:
  name: "desk_control"
  base_button_name: "Desk Control Button"
  ap_ssid: "Desk Control Fallback Hotspot"

# See for reusing: https://esphome.io/guides/configuration-types.html#config-substitutions
esphome:
  <<: !include .board-config.yaml
  includes:
    - desk_height_sensor.h
  on_boot:
    then:
      - if:
          condition:
            lambda: 'return isnan(id(desk_control_height).state);'
          then:
            - switch.turn_on: red
            - delay: 10ms
            - switch.turn_off: red

<<: !include .base-config.yaml

####
# Section -- Desk Controll
####

# UART2
uart:
  baud_rate: 1000
  rx_pin: 16
  data_bits: 8
  parity: EVEN
  stop_bits: 1
  id: desk_height_uart_bus

# Custom height sensor
sensor:
  ####
  # Desk Control
  ####
  - platform: custom
    lambda: |-
      auto desk_height_sensor = new DeskHeightSensor(id(desk_height_uart_bus));
      App.register_component(desk_height_sensor);
      return {desk_height_sensor};
    sensors:
      id: desk_control_height
      name: Desk Control Height
      unit_of_measurement: "cm"
      icon: mdi:human-male-height

switch:
  # ID is wire color of "Desk Control 520"
  - platform: gpio
    pin: 32
    id: blue
  - platform: gpio
    pin: 33
    id: green
  - platform: gpio
    pin: 25
    id: yellow
  - platform: gpio
    pin: 26
    id: red

  # Define button
  - platform: template
    id: desk_control_button_1
    name: ${base_button_name} 1
    icon: mdi:numeric-1-circle
    lambda: |-
      if (id(blue).state && !(id(red).state || id(green).state || id(yellow).state)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - if:
          condition:
            and:
              - switch.is_off: desk_control_button_2
              - switch.is_off: desk_control_button_3
              - switch.is_off: desk_control_button_4
              - switch.is_off: desk_control_button_up
              - switch.is_off: desk_control_button_down
          then:
            - switch.turn_on: blue
            - delay: 12s
            - if:
                condition:
                  switch.is_on: desk_control_button_1
                then:
                  - switch.turn_off: blue
    turn_off_action:
      - switch.turn_off: blue

  - platform: template
    id: desk_control_button_2
    name: ${base_button_name} 2
    icon: mdi:numeric-2-circle
    lambda: |-
      if (id(yellow).state && !(id(red).state || id(green).state || id(blue).state)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - if:
          condition:
            and:
              - switch.is_off: desk_control_button_1
              - switch.is_off: desk_control_button_3
              - switch.is_off: desk_control_button_4
              - switch.is_off: desk_control_button_up
              - switch.is_off: desk_control_button_down
          then:
            - switch.turn_on: yellow
            - delay: 12s
            - if:
                condition:
                  switch.is_on: desk_control_button_2
                then:
                  - switch.turn_off: yellow
    turn_off_action:
      - switch.turn_off: yellow

  - platform: template
    id: desk_control_button_3
    name: ${base_button_name} 3
    icon: mdi:numeric-3-circle
    lambda: |-
      if (id(yellow).state && id(green).state && !(id(red).state || id(blue).state)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - if:
          condition:
            and:
              - switch.is_off: desk_control_button_1
              - switch.is_off: desk_control_button_2
              - switch.is_off: desk_control_button_4
              - switch.is_off: desk_control_button_up
              - switch.is_off: desk_control_button_down
          then:
            - switch.turn_on: yellow
            - switch.turn_on: green
            - delay: 12s
            - if:
                condition:
                  switch.is_on: desk_control_button_3
                then:
                  - switch.turn_off: yellow
                  - switch.turn_off: green
    turn_off_action:
      - switch.turn_off: yellow
      - switch.turn_off: green

  - platform: template
    id: desk_control_button_4
    name: ${base_button_name} 4
    icon: mdi:numeric-4-circle
    lambda: |-
      if (id(blue).state && id(green).state && !(id(red).state || id(yellow).state)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - if:
          condition:
            and:
              - switch.is_off: desk_control_button_1
              - switch.is_off: desk_control_button_2
              - switch.is_off: desk_control_button_3
              - switch.is_off: desk_control_button_up
              - switch.is_off: desk_control_button_down
          then:
            - switch.turn_on: blue
            - switch.turn_on: green
            - delay: 12s
            - if:
                condition:
                  switch.is_on: desk_control_button_4
                then:
                  - switch.turn_off: blue
                  - switch.turn_off: green
    turn_off_action:
      - switch.turn_off: blue
      - switch.turn_off: green

  - platform: template
    id: desk_control_button_up
    name: ${base_button_name} Up
    icon: mdi:arrow-up
    lambda: |-
      if (id(red).state && !(id(blue).state || id(green).state || id(yellow).state)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - if:
          condition:
            and:
              - switch.is_off: desk_control_button_1
              - switch.is_off: desk_control_button_2
              - switch.is_off: desk_control_button_3
              - switch.is_off: desk_control_button_4
              - switch.is_off: desk_control_button_down
          then:
            - switch.turn_on: red
    turn_off_action:
      - switch.turn_off: red

  - platform: template
    id: desk_control_button_down
    name: ${base_button_name} Down
    icon: mdi:arrow-down
    lambda: |-
      if (id(green).state && !(id(red).state || id(blue).state || id(yellow).state)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - if:
          condition:
            and:
              - switch.is_off: desk_control_button_1
              - switch.is_off: desk_control_button_2
              - switch.is_off: desk_control_button_3
              - switch.is_off: desk_control_button_4
              - switch.is_off: desk_control_button_up
          then:
            - switch.turn_on: green
    turn_off_action:
      - switch.turn_off: green

  #### Office AC
  - platform: template
    name: 'Office AC Preset'
    id: office_ac_preset
    icon: mdi:cached
    turn_on_action:
      - climate.control:
          id: office_ac
          mode: COOL
          target_temperature: 24°C
          fan_mode: AUTO
          swing_mode: VERTICAL

  # - platform: template
  #   name: "Office AC Preset"
  #   id: office_ac_preset
  #   icon: mdi:cached
  #   turn_on_action:
  #     - remote_transmitter.transmit_raw:
  #         code: [-4426, 4376, -558, 1600, -555, 1625, -442, 1711, -556, 1598, -558, 532, -525, 547, -546, 1626, -493, 576, -555, 530, -559, 534, -441, 622, -558, 532, -555, 1600, -557, 1603, -551, 533, -559, 1601, -554, 533, -558, 514, -462, 621, -558, 531, -554, 518, -544, 1631, -519, 551, -552, 1625, -442, 1713, -557, 1596, -560, 1604, -546, 1628, -492, 1663, -558, 517, -461, 1711, -555, 518, -516, 566, -557, 533, -522, 550, -528, 556, -559, 533, -443, 624, -551, 535, -558, 1599, -557, 532, -549, 1601, -559, 1600, -529, 1648, -440, 623, -553, 535, -556, 517, -488, 593, -556, 534, -522, 548, -546, 538, -557, 533, -490, 578, -553, 533, -555, 538, -440, 1711, -553, 519, -517, 565, -558, 531, -520, 550, -552, 532, -558, 532, -444, 624, -554, 533, -533, 539, -461, 621, -556, 1605, -544, 539, -535, 556, -493, 576, -529, 556, -557, 1602, -530, 556, -557, 516, -515, 566, -534, 559, -520, 548, -552, 534, -559, 1598, -530, 557, -534, 541, -459, 1711, -550, 521, -517, 1655, -518, 550, -551, 533, -559, 1600, -555, 1627, -441, 6169, -4420, 4379, -559, 1603, -528, 1648, -444, 1712, -557, 1599, -533, 558, -525, 547, -544, 1629, -518, 552, -553, 534, -556, 537, -442, 622, -532, 557, -532, 1622, -558, 1604, -523, 561, -557, 1601, -529, 557, -534, 560, -440, 623, -555, 534, -527, 544, -518, 1654, -520, 549, -552, 1625, -442, 1710, -558, 1597, -558, 1603, -522, 1655, -491, 1664, -534, 560, -441, 1711, -554, 519, -515, 568, -558, 531, -522, 548, -551, 535, -534, 557, -444, 624, -530, 558, -532, 1623, -556, 532, -527, 1629, -534, 1626, -552, 1626, -441, 625, -529, 557, -534, 560, -468, 593, -557, 534, -524, 546, -527, 558, -556, 534, -491, 578, -529, 557, -533, 560, -441, 1711, -554, 519, -516, 566, -557, 533, -520, 550, -550, 535, -558, 534, -443, 623, -554, 535, -532, 541, -460, 621, -555, 1605, -520, 563, -560, 532, -516, 552, -553, 533, -557, 1602, -532, 555, -559, 513, -490, 594, -556, 533, -522, 548, -523, 562, -556, 1601, -553, 533, -557, 537, -441, 1710, -530, 543, -517, 1656, -520, 550, -551, 533, -557, 1600, -554, 1607, -460]

  - platform: template
    name: "Office AC Swing"
    id: office_ac_swing
    icon: mdi:fan
    turn_on_action:
      - climate.control:
          id: office_ac
          mode: COOL
          target_temperature: 24°C
          fan_mode: AUTO
          swing_mode: VERTICAL
    # turn_on_action:
    #   - remote_transmitter.transmit_raw:
    #       code: [-4421, 4377, -558, 1602, -548, 1625, -441, 1712, -558, 1596, -557, 533, -523, 547, -548, 1628, -492, 577, -552, 535, -557, 519, -458, 622, -556, 533, -555, 1602, -557, 1602, -528, 559, -558, 1599, -532, 558, -556, 519, -460, 621, -557, 532, -553, 521, -543, 539, -536, 556, -495, 1664, -559, 1601, -554, 1608, -490, 1686, -522, 1633, -559, 1602, -555, 1608, -460, 1715, -529, 544, -517, 567, -557, 532, -521, 1636, -558, 535, -442, 624, -555, 534, -559, 513, -461, 1713, -526, 546, -522, 561, -561, 533, -494, 575, -554, 534, -557, 537, -441, 625, -531, 1632, -489, 591, -559, 535, -521, 1636, -560, 532, -456, 614, -555, 531, -558, 519, -459, 623, -558, 6042, -4376, 4436, -444, 1713, -558, 1596, -535, 1629, -523, 1653, -492, 576, -554, 534, -557, 1602, -556, 533, -557, 517, -492, 592, -557, 534, -546, 527, -545, 1633, -465, 1690, -559, 536, -440, 1712, -529, 545, -517, 567, -534, 558, -520, 550, -552, 535, -557, 536, -441, 624, -531, 1653, -441, 1710, -526, 1630, -557, 1601, -552, 1630, -442, 1712, -557, 1600, -557, 1605, -526, 558, -560, 531, -444, 625, -531, 1632, -460, 623, -557, 532, -529, 546, -519, 566, -557, 1604, -550, 535, -558, 537, -441, 623, -554, 534, -560, 515, -488, 594, -557, 532, -549, 1609, -558, 533, -493, 577, -553, 1627, -441, 623, -556, 533, -555, 517, -518, 565, -536, 556, -521]

####
# Section -- Office AC
####
#  Notes
#
#  Receiver need to be non-inverted when learning the commands, and inverted
#  when you want to use the return value from the AC unit.
####
### IR Receiver
remote_receiver:
  id: rcvr
  pin:
    number: 12
    inverted: True
    mode: INPUT_PULLUP
  # tolerance: 55%
  # dump: raw

### IR Transmit

# https://www.esphome.io/components/remote_transmitter.html
remote_transmitter:
  id: tamtr
  pin: 14
  carrier_duty_percent: 50%

# https://esphome.io/components/climate/ir_climate.html
climate:
  - platform: toshiba
    id: office_ac
    name: 'Office AC'
    receiver_id: rcvr
    transmitter_id: tamtr
