substitutions:
  base_button_name: "Desk Control Button"
# See for reusing: https://esphome.io/guides/configuration-types.html#config-substitutions
esphome:
  name: desk_control
  platform: ESP32
  board: esp32dev
  platformio_options:
    platform: espressif32
    board: az-delivery-devkit-v4
    board_build.mcu: esp32
    board_build.f_cpu: 240000000L

wifi:
  ssid: !secret ssid
  password: !secret password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Desk Control Fallback Hotspot"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret password

ota:
  password: !secret password

sensor:
  - platform: adc
    pin: 35
    internal: true
    id: desk_control_display

switch:
  # id is wire color
  - platform: gpio
    pin: 32
    id: blue
  - platform: gpio
    pin: 33
    id: green
  - platform: gpio
    pin: 25
    id: yellow
  - platform: gpio
    pin: 26
    id: red

  - platform: template
    id: desk_control_button_1
    name: ${base_button_name} 1
    icon: mdi:numeric-1-circle
    lambda: |-
      if (id(blue).state && !(id(red).state || id(green).state || id(yellow).state)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - if:
          condition:
            and:
              - switch.is_off: desk_control_button_2
              - switch.is_off: desk_control_button_3
              - switch.is_off: desk_control_button_4
              - switch.is_off: desk_control_button_up
              - switch.is_off: desk_control_button_down
          then:
            - switch.turn_on: blue
            - delay: 14s
            - if:
                condition:
                  switch.is_on: desk_control_button_1
                then:
                  - switch.turn_off: blue
    turn_off_action:
      - switch.turn_off: blue

  - platform: template
    id: desk_control_button_2
    name: ${base_button_name} 2
    icon: mdi:numeric-2-circle
    lambda: |-
      if (id(yellow).state && !(id(red).state || id(green).state || id(blue).state)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - if:
          condition:
            and:
              - switch.is_off: desk_control_button_1
              - switch.is_off: desk_control_button_3
              - switch.is_off: desk_control_button_4
              - switch.is_off: desk_control_button_up
              - switch.is_off: desk_control_button_down
          then:
            - switch.turn_on: yellow
            - delay: 14s
            - if:
                condition:
                  switch.is_on: desk_control_button_2
                then:
                  - switch.turn_off: yellow
    turn_off_action:
      - switch.turn_off: yellow

  - platform: template
    id: desk_control_button_3
    name: ${base_button_name} 3
    icon: mdi:numeric-3-circle
    lambda: |-
      if (id(yellow).state && id(green).state && !(id(red).state || id(blue).state)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - if:
          condition:
            and:
              - switch.is_off: desk_control_button_1
              - switch.is_off: desk_control_button_2
              - switch.is_off: desk_control_button_4
              - switch.is_off: desk_control_button_up
              - switch.is_off: desk_control_button_down
          then:
            - switch.turn_on: yellow
            - switch.turn_on: green
            - delay: 14s
            - if:
                condition:
                  switch.is_on: desk_control_button_3
                then:
                  - switch.turn_off: yellow
                  - switch.turn_off: green
    turn_off_action:
      - switch.turn_off: yellow
      - switch.turn_off: green

  - platform: template
    id: desk_control_button_4
    name: ${base_button_name} 4
    icon: mdi:numeric-4-circle
    lambda: |-
      if (id(blue).state && id(green).state && !(id(red).state || id(yellow).state)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - if:
          condition:
            and:
              - switch.is_off: desk_control_button_1
              - switch.is_off: desk_control_button_2
              - switch.is_off: desk_control_button_3
              - switch.is_off: desk_control_button_up
              - switch.is_off: desk_control_button_down
          then:
            - switch.turn_on: blue
            - switch.turn_on: green
            - delay: 14s
            - if:
                condition:
                  switch.is_on: desk_control_button_4
                then:
                  - switch.turn_off: blue
                  - switch.turn_off: green
    turn_off_action:
      - switch.turn_off: blue
      - switch.turn_off: green

  - platform: template
    id: desk_control_button_up
    name: ${base_button_name} Up
    icon: mdi:arrow-up
    lambda: |-
      if (id(red).state && !(id(blue).state || id(green).state || id(yellow).state)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - if:
          condition:
            and:
              - switch.is_off: desk_control_button_1
              - switch.is_off: desk_control_button_2
              - switch.is_off: desk_control_button_3
              - switch.is_off: desk_control_button_4
              - switch.is_off: desk_control_button_down
          then:
            - switch.turn_on: red
    turn_off_action:
      - switch.turn_off: red

  - platform: template
    id: desk_control_button_down
    name: ${base_button_name} Down
    icon: mdi:arrow-down
    lambda: |-
      if (id(green).state && !(id(red).state || id(blue).state || id(yellow).state)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - if:
          condition:
            and:
              - switch.is_off: desk_control_button_1
              - switch.is_off: desk_control_button_2
              - switch.is_off: desk_control_button_3
              - switch.is_off: desk_control_button_4
              - switch.is_off: desk_control_button_up
          then:
            - switch.turn_on: green
    turn_off_action:
      - switch.turn_off: green
