substitutions:
  base_button_name: "Fan Button"

esphome:
  name: fan
  platform: ESP32
  board: esp32dev
  platformio_options:
    platform: espressif32
    board: az-delivery-devkit-v4
    board_build.mcu: esp32
    board_build.f_cpu: 240000000L

wifi:
  ssid: !secret ssid
  password: !secret password
  fast_connect: true


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fan Fallback Hotspot"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret password

ota:
  password: !secret password


switch:
  # id is wire color
  - platform: gpio
    pin: 33
    id: fan_power
    name: Fan Power
    icon: mdi:power

remote_receiver:
  pin: 32
  dump: all
