substitutions:
  name: office-light-switch
  ap_ssid: Office Light Switch FH
  ip: 192.168.1.37
  channel_1: Office Front Light
  channel_2: Office Back Light
  max_power: "2000.0"
  max_temp: "70.0"

<<: !include .shelly-2.5-as-light-template.yaml
