substitutions:
  name: parlor-shutter-relay
  ap_ssid: Parlor Shutter Relay FH
  ip: 192.168.1.43
  channel_1: Parlor Shutter Up
  channel_2: Parlor Shutter Down
  max_power: "2000.0"
  max_temp: "70.0"

<<: !include .shelly-2.5-as-relay-template.yaml
