substitutions:
  name: status-board
  ap_ssid: Status Board FH
  ip: 192.168.1.28

esphome:
  <<: !include .board-config-az-delivery-devkit-v4.yaml

<<: !include .base-config.yaml

# logger:
#   level: VERY_VERBOSE

deep_sleep:
  run_duration: 1min
  # sleep_duration: 10min
  wakeup_pin: 35

text_sensor:
  - platform: homeassistant
    id: person_christian
    entity_id: person.christian_schwarzgruber

binary_sensor:
  - platform: homeassistant
    id: binary_sensor_office
    entity_id: binary_sensor.office_window_sensor

  - platform: homeassistant
    id: binary_sensor_parlor
    entity_id: binary_sensor.parlor_window_sensor

  - platform: homeassistant
    id: binary_sensor_bedroom
    entity_id: binary_sensor.bedroom_window_sensor

  - platform: homeassistant
    id: binary_sensor_lower_kitchen
    entity_id: binary_sensor.lower_kitchen_window_sensor

  - platform: homeassistant
    id: binary_sensor_upstairs
    entity_id: binary_sensor.upstairs_window_sensor

  - platform: homeassistant
    id: binary_sensor_balcony
    entity_id: binary_sensor.balcony_door_sensor

  - platform: template
    id: binary_sensor_office_template
    lambda: |
      if (id(binary_sensor_office).state) {
        id(office).turn_on();
        return true;
      } else {
        id(office).turn_off();
        return false;
      }

  - platform: template
    id: binary_sensor_parlor_template
    lambda: |
      if (id(binary_sensor_parlor).state) {
        id(parlor).turn_on();
        return true;
      } else {
        id(parlor).turn_off();
        return false;
      }

  - platform: template
    id: binary_sensor_bedroom_template
    lambda: |
      if (id(binary_sensor_bedroom).state) {
        id(bedroom).turn_on();
        return true;
      } else {
        id(bedroom).turn_off();
        return false;
      }

  - platform: template
    id: binary_sensor_lower_kitchen_template
    lambda: |
      if (id(binary_sensor_lower_kitchen).state) {
        id(lower_kitchen).turn_on();
        return true;
      } else {
        id(lower_kitchen).turn_off();
        return false;
      }

  - platform: template
    id: binary_sensor_balcony_template
    lambda: |
      if (id(binary_sensor_balcony).state) {
        id(balcony).turn_on();
        return true;
      } else {
        id(balcony).turn_off();
        return false;
      }

  - platform: template
    id: binary_sensor_upstairs_template
    lambda: |
      if (id(binary_sensor_upstairs).state) {
        id(upstairs).turn_on();
        return true;
      } else {
        id(upstairs).turn_off();
        return false;
      }

  - platform: template
    id: person_christian_template
    lambda: |
      if (id(person_christian).state.compare("not_home") == 0) {
        id(chris).turn_on();
        return true;
      } else {
        id(chris).turn_off();
        return false;
      }

switch:
  - platform: gpio
    pin: 12
    id: chris
  - platform: gpio
    pin: 14
    id: office
  - platform: gpio
    pin: 27
    id: parlor
  - platform: gpio
    pin: 26
    id: bedroom
  - platform: gpio
    pin: 25
    id: lower_kitchen
  - platform: gpio
    pin: 33
    id: upstairs
  - platform: gpio
    pin: 32
    id: balcony
