substitutions:
  name: toshiba-ac
  ap_ssid: Toshiba AC Fallback Hotspot

esphome:
  <<: !include .board-config.yaml

<<: !include .base-config.yaml

# logger:
#   level: VERY_VERBOSE

### Receiver RF
remote_receiver:
  id: rcvr
  pin:
    number: 32
    mode: INPUT_PULLUP
    inverted: True
  dump: all
  # dump: raw

### Transmit IR

# https://www.esphome.io/components/remote_transmitter.html
remote_transmitter:
  id: tsmtr
  pin: 27
  carrier_duty_percent: 50%

# https://esphome.io/components/climate/ir_climate.html
climate:
 - platform: toshiba
   id: toshiba_ac
   name: Toshiba AC
   transmitter_id: tsmtr
   receiver_id: rcvr
   model: MODEL_2

switch:
  - platform: template
    name: Toshiba AC Preset
    id: toshiba_ac_preset
    icon: mdi:cached
    turn_on_action:
      - climate.control:
          id: toshiba_ac
          mode: COOL
          target_temperature: 24°C
          fan_mode: AUTO
          swing_mode: 'OFF'
