- alias: Turn on/off presence using lower kitchen switch
  description: ''
  trigger:
  - device_id: c2cff687003dd88942aa8597fe9f8734
    domain: deconz
    platform: device
    type: remote_button_long_press
    subtype: turn_off
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.presence
        state: 'on'
      sequence:
      - repeat:
          count: '2'
          sequence:
          - type: flash
            device_id: 9a999d4e84bd4c8eb7c7779363b97b26
            entity_id: light.front_floor
            domain: light
          - delay: 00:00:10
      - repeat:
          count: '2'
          sequence:
          - type: flash
            device_id: 9a999d4e84bd4c8eb7c7779363b97b26
            entity_id: light.front_floor
            domain: light
          - delay: 00:00:5
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.presence
        entity_id: input_boolean.presence
    - conditions:
      - condition: state
        entity_id: input_boolean.presence
        state: 'off'
      sequence:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.presence
        entity_id: input_boolean.presence
      - repeat:
          count: '2'
          sequence:
          - type: flash
            device_id: 9a999d4e84bd4c8eb7c7779363b97b26
            entity_id: light.front_floor
            domain: light
    default: []
  mode: single
- alias: Cancel automation.lower_kitchen_switch_turn_off_presence
  description: ''
  trigger:
  - device_id: c2cff687003dd88942aa8597fe9f8734
    domain: deconz
    platform: device
    type: remote_button_long_press
    subtype: turn_on
  condition:
  - condition: template
    value_template: '{{ state_attr(''automation.lower_kitchen_switch_turn_off_on_presence'',
      ''current'')  | int == 1 }}'
  action:
  - service: automation.turn_off
    data:
      entity_id: automation.lower_kitchen_switch_turn_off_on_presence
    entity_id: automation.lower_kitchen_switch_turn_off_on_presence
  - service: automation.turn_on
    data:
      entity_id: automation.lower_kitchen_switch_turn_off_on_presence
    entity_id: automation.lower_kitchen_switch_turn_off_on_presence
  mode: single
